// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  familyId: __t.u64(),
  kind: __t.string(),
  name: __t.string(),
  instruction: __t.string(),
  times: __t.array(__t.string()),
  reason: __t.option(__t.string()),
  source: __t.string(),
  effectiveDate: __t.string(),
};
