// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  FinderSighting,
} from "./types";


export default __t.row({
  tokenHash: __t.string().name("token_hash"),
  sessionHash: __t.option(__t.string()).name("session_hash"),
  familyId: __t.u64().name("family_id"),
  personId: __t.identity().name("person_id"),
  expiresAt: __t.timestamp().name("expires_at"),
  usedAt: __t.option(__t.timestamp()).name("used_at"),
  get sightings() {
    return __t.array(FinderSighting);
  },
});
