// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcknowledgeAlertReducer from "./acknowledge_alert_reducer";
import AddCareInstructionReducer from "./add_care_instruction_reducer";
import AddFamilyMemberReducer from "./add_family_member_reducer";
import AnswerReminderReducer from "./answer_reminder_reducer";
import AnswerTextedReminderReducer from "./answer_texted_reminder_reducer";
import ApproveClinicianShareReducer from "./approve_clinician_share_reducer";
import BackfillFounderCareGrantsReducer from "./backfill_founder_care_grants_reducer";
import CancelAppointmentReducer from "./cancel_appointment_reducer";
import ClaimAlertDeliveryReducer from "./claim_alert_delivery_reducer";
import ConfirmAppointmentReducer from "./confirm_appointment_reducer";
import ConfirmReminderReducer from "./confirm_reminder_reducer";
import CreateExercisePlanReducer from "./create_exercise_plan_reducer";
import CreateFamilyReducer from "./create_family_reducer";
import CreateFamilyInviteReducer from "./create_family_invite_reducer";
import CreateFinderLinkReducer from "./create_finder_link_reducer";
import CreateReminderReducer from "./create_reminder_reducer";
import CreateReportReducer from "./create_report_reducer";
import DeleteFamilyReducer from "./delete_family_reducer";
import DeleteMedicineArPinReducer from "./delete_medicine_ar_pin_reducer";
import DeleteReminderReducer from "./delete_reminder_reducer";
import ForgetMedicineSightingReducer from "./forget_medicine_sighting_reducer";
import JoinFamilyByInviteReducer from "./join_family_by_invite_reducer";
import LinkFinchnodeSubjectReducer from "./link_finchnode_subject_reducer";
import MarkAlertDeliveryFailedReducer from "./mark_alert_delivery_failed_reducer";
import MarkAlertDeliverySentReducer from "./mark_alert_delivery_sent_reducer";
import MarkAlertDeliveryUnavailableReducer from "./mark_alert_delivery_unavailable_reducer";
import MarkMedicineNotFoundReducer from "./mark_medicine_not_found_reducer";
import MigrateMedicineMembersReducer from "./migrate_medicine_members_reducer";
import OpenCareNeedReducer from "./open_care_need_reducer";
import OpenFinderLinkReducer from "./open_finder_link_reducer";
import PostAlertMessageReducer from "./post_alert_message_reducer";
import QueueReportEmailReducer from "./queue_report_email_reducer";
import RaiseAlertReducer from "./raise_alert_reducer";
import RecordDeliveryEventReducer from "./record_delivery_event_reducer";
import RecordExerciseEventReducer from "./record_exercise_event_reducer";
import RecordMealFactReducer from "./record_meal_fact_reducer";
import RecordReminderDeliveryReducer from "./record_reminder_delivery_reducer";
import RecordSampleReducer from "./record_sample_reducer";
import RecordTripEventReducer from "./record_trip_event_reducer";
import RememberByFinderLinkReducer from "./remember_by_finder_link_reducer";
import RememberMedicineReducer from "./remember_medicine_reducer";
import RemoveAlertThresholdReducer from "./remove_alert_threshold_reducer";
import RenameFamilyReducer from "./rename_family_reducer";
import ReportLocationReducer from "./report_location_reducer";
import RequestAppointmentReducer from "./request_appointment_reducer";
import RespondToCareNeedReducer from "./respond_to_care_need_reducer";
import ReviewAppointmentSummaryReducer from "./review_appointment_summary_reducer";
import RevokeClinicianShareReducer from "./revoke_clinician_share_reducer";
import RevokeLocationShareReducer from "./revoke_location_share_reducer";
import SaveCareProfileReducer from "./save_care_profile_reducer";
import SaveCookingProfileReducer from "./save_cooking_profile_reducer";
import SaveMedicineArPinReducer from "./save_medicine_ar_pin_reducer";
import SendClinicianShareReducer from "./send_clinician_share_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetAlertThresholdReducer from "./set_alert_threshold_reducer";
import SetCareGrantReducer from "./set_care_grant_reducer";
import SetContactLadderReducer from "./set_contact_ladder_reducer";
import SetFamilyPushTokenReducer from "./set_family_push_token_reducer";
import SetMedicineMemoryReducer from "./set_medicine_memory_reducer";
import SetMyNameReducer from "./set_my_name_reducer";
import SetReminderSettingsReducer from "./set_reminder_settings_reducer";
import SetReportEmailSettingsReducer from "./set_report_email_settings_reducer";
import SetSpeakerSettingsReducer from "./set_speaker_settings_reducer";
import SettleReportEmailReducer from "./settle_report_email_reducer";
import SettleWearerTextReducer from "./settle_wearer_text_reducer";
import ShareLocationReducer from "./share_location_reducer";
import SuggestAppointmentReducer from "./suggest_appointment_reducer";
import UpdateAppointmentPrepReducer from "./update_appointment_prep_reducer";
import UpdateReportReducer from "./update_report_reducer";
import VerifyCareInstructionReducer from "./verify_care_instruction_reducer";
import VerifyExercisePlanReducer from "./verify_exercise_plan_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import FinderLinksRow from "./finder_links_table";
import MyAcknowledgementsRow from "./my_acknowledgements_table";
import MyAlertDeliveriesRow from "./my_alert_deliveries_table";
import MyAlertThresholdsRow from "./my_alert_thresholds_table";
import MyAlertsRow from "./my_alerts_table";
import MyAppointmentsRow from "./my_appointments_table";
import MyCareGrantsRow from "./my_care_grants_table";
import MyCareInstructionsRow from "./my_care_instructions_table";
import MyCareNeedsRow from "./my_care_needs_table";
import MyCareProfilesRow from "./my_care_profiles_table";
import MyClinicianSharesRow from "./my_clinician_shares_table";
import MyContactAttemptsRow from "./my_contact_attempts_table";
import MyContactLaddersRow from "./my_contact_ladders_table";
import MyCookingProfilesRow from "./my_cooking_profiles_table";
import MyDeliveryEventsRow from "./my_delivery_events_table";
import MyExerciseEventsRow from "./my_exercise_events_table";
import MyExercisePlansRow from "./my_exercise_plans_table";
import MyFamiliesRow from "./my_families_table";
import MyFamilyInvitesRow from "./my_family_invites_table";
import MyFamilyMembersRow from "./my_family_members_table";
import MyFamilyPeopleRow from "./my_family_people_table";
import MyFinchnodeLinksRow from "./my_finchnode_links_table";
import MyHealthSamplesRow from "./my_health_samples_table";
import MyLocationSharesRow from "./my_location_shares_table";
import MyLocationsRow from "./my_locations_table";
import MyMealFactsRow from "./my_meal_facts_table";
import MyMedicineArPinsRow from "./my_medicine_ar_pins_table";
import MyMedicinePlacesRow from "./my_medicine_places_table";
import MyMedicineSightingsRow from "./my_medicine_sightings_table";
import MyMessagesRow from "./my_messages_table";
import MyPushTokensRow from "./my_push_tokens_table";
import MyReminderEventsRow from "./my_reminder_events_table";
import MyReminderOccurrencesRow from "./my_reminder_occurrences_table";
import MyReminderSettingsRow from "./my_reminder_settings_table";
import MyRemindersRow from "./my_reminders_table";
import MyReportEmailSettingsRow from "./my_report_email_settings_table";
import MyReportEmailsRow from "./my_report_emails_table";
import MyReportsRow from "./my_reports_table";
import MySpeakerSettingsRow from "./my_speaker_settings_table";
import MyTripEventsRow from "./my_trip_events_table";
import PendingAlertDeliveriesRow from "./pending_alert_deliveries_table";
import PendingWearerTextsRow from "./pending_wearer_texts_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  finderLinks: __table({
    name: 'finder_links',
    indexes: [
    ],
    constraints: [
    ],
  }, FinderLinksRow),
  myAcknowledgements: __table({
    name: 'my_acknowledgements',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAcknowledgementsRow),
  myAlertDeliveries: __table({
    name: 'my_alert_deliveries',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAlertDeliveriesRow),
  myAlertThresholds: __table({
    name: 'my_alert_thresholds',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAlertThresholdsRow),
  myAlerts: __table({
    name: 'my_alerts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAlertsRow),
  myAppointments: __table({
    name: 'my_appointments',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAppointmentsRow),
  myCareGrants: __table({
    name: 'my_care_grants',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCareGrantsRow),
  myCareInstructions: __table({
    name: 'my_care_instructions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCareInstructionsRow),
  myCareNeeds: __table({
    name: 'my_care_needs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCareNeedsRow),
  myCareProfiles: __table({
    name: 'my_care_profiles',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCareProfilesRow),
  myClinicianShares: __table({
    name: 'my_clinician_shares',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClinicianSharesRow),
  myContactAttempts: __table({
    name: 'my_contact_attempts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyContactAttemptsRow),
  myContactLadders: __table({
    name: 'my_contact_ladders',
    indexes: [
    ],
    constraints: [
    ],
  }, MyContactLaddersRow),
  myCookingProfiles: __table({
    name: 'my_cooking_profiles',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCookingProfilesRow),
  myDeliveryEvents: __table({
    name: 'my_delivery_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDeliveryEventsRow),
  myExerciseEvents: __table({
    name: 'my_exercise_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyExerciseEventsRow),
  myExercisePlans: __table({
    name: 'my_exercise_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, MyExercisePlansRow),
  myFamilies: __table({
    name: 'my_families',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFamiliesRow),
  myFamilyInvites: __table({
    name: 'my_family_invites',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFamilyInvitesRow),
  myFamilyMembers: __table({
    name: 'my_family_members',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFamilyMembersRow),
  myFamilyPeople: __table({
    name: 'my_family_people',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFamilyPeopleRow),
  myFinchnodeLinks: __table({
    name: 'my_finchnode_links',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFinchnodeLinksRow),
  myHealthSamples: __table({
    name: 'my_health_samples',
    indexes: [
    ],
    constraints: [
    ],
  }, MyHealthSamplesRow),
  myLocationShares: __table({
    name: 'my_location_shares',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLocationSharesRow),
  myLocations: __table({
    name: 'my_locations',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLocationsRow),
  myMealFacts: __table({
    name: 'my_meal_facts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMealFactsRow),
  myMedicineArPins: __table({
    name: 'my_medicine_ar_pins',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMedicineArPinsRow),
  myMedicinePlaces: __table({
    name: 'my_medicine_places',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMedicinePlacesRow),
  myMedicineSightings: __table({
    name: 'my_medicine_sightings',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMedicineSightingsRow),
  myMessages: __table({
    name: 'my_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMessagesRow),
  myPushTokens: __table({
    name: 'my_push_tokens',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPushTokensRow),
  myReminderEvents: __table({
    name: 'my_reminder_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReminderEventsRow),
  myReminderOccurrences: __table({
    name: 'my_reminder_occurrences',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReminderOccurrencesRow),
  myReminderSettings: __table({
    name: 'my_reminder_settings',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReminderSettingsRow),
  myReminders: __table({
    name: 'my_reminders',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRemindersRow),
  myReportEmailSettings: __table({
    name: 'my_report_email_settings',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReportEmailSettingsRow),
  myReportEmails: __table({
    name: 'my_report_emails',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReportEmailsRow),
  myReports: __table({
    name: 'my_reports',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReportsRow),
  mySpeakerSettings: __table({
    name: 'my_speaker_settings',
    indexes: [
    ],
    constraints: [
    ],
  }, MySpeakerSettingsRow),
  myTripEvents: __table({
    name: 'my_trip_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTripEventsRow),
  pendingAlertDeliveries: __table({
    name: 'pending_alert_deliveries',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingAlertDeliveriesRow),
  pendingWearerTexts: __table({
    name: 'pending_wearer_texts',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingWearerTextsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("acknowledge_alert", AcknowledgeAlertReducer),
  __reducerSchema("add_care_instruction", AddCareInstructionReducer),
  __reducerSchema("add_family_member", AddFamilyMemberReducer),
  __reducerSchema("answer_reminder", AnswerReminderReducer),
  __reducerSchema("answer_texted_reminder", AnswerTextedReminderReducer),
  __reducerSchema("approve_clinician_share", ApproveClinicianShareReducer),
  __reducerSchema("backfill_founder_care_grants", BackfillFounderCareGrantsReducer),
  __reducerSchema("cancel_appointment", CancelAppointmentReducer),
  __reducerSchema("claim_alert_delivery", ClaimAlertDeliveryReducer),
  __reducerSchema("confirm_appointment", ConfirmAppointmentReducer),
  __reducerSchema("confirm_reminder", ConfirmReminderReducer),
  __reducerSchema("create_exercise_plan", CreateExercisePlanReducer),
  __reducerSchema("create_family", CreateFamilyReducer),
  __reducerSchema("create_family_invite", CreateFamilyInviteReducer),
  __reducerSchema("create_finder_link", CreateFinderLinkReducer),
  __reducerSchema("create_reminder", CreateReminderReducer),
  __reducerSchema("create_report", CreateReportReducer),
  __reducerSchema("delete_family", DeleteFamilyReducer),
  __reducerSchema("delete_medicine_ar_pin", DeleteMedicineArPinReducer),
  __reducerSchema("delete_reminder", DeleteReminderReducer),
  __reducerSchema("forget_medicine_sighting", ForgetMedicineSightingReducer),
  __reducerSchema("join_family_by_invite", JoinFamilyByInviteReducer),
  __reducerSchema("link_finchnode_subject", LinkFinchnodeSubjectReducer),
  __reducerSchema("mark_alert_delivery_failed", MarkAlertDeliveryFailedReducer),
  __reducerSchema("mark_alert_delivery_sent", MarkAlertDeliverySentReducer),
  __reducerSchema("mark_alert_delivery_unavailable", MarkAlertDeliveryUnavailableReducer),
  __reducerSchema("mark_medicine_not_found", MarkMedicineNotFoundReducer),
  __reducerSchema("migrate_medicine_members", MigrateMedicineMembersReducer),
  __reducerSchema("open_care_need", OpenCareNeedReducer),
  __reducerSchema("open_finder_link", OpenFinderLinkReducer),
  __reducerSchema("post_alert_message", PostAlertMessageReducer),
  __reducerSchema("queue_report_email", QueueReportEmailReducer),
  __reducerSchema("raise_alert", RaiseAlertReducer),
  __reducerSchema("record_delivery_event", RecordDeliveryEventReducer),
  __reducerSchema("record_exercise_event", RecordExerciseEventReducer),
  __reducerSchema("record_meal_fact", RecordMealFactReducer),
  __reducerSchema("record_reminder_delivery", RecordReminderDeliveryReducer),
  __reducerSchema("record_sample", RecordSampleReducer),
  __reducerSchema("record_trip_event", RecordTripEventReducer),
  __reducerSchema("remember_by_finder_link", RememberByFinderLinkReducer),
  __reducerSchema("remember_medicine", RememberMedicineReducer),
  __reducerSchema("remove_alert_threshold", RemoveAlertThresholdReducer),
  __reducerSchema("rename_family", RenameFamilyReducer),
  __reducerSchema("report_location", ReportLocationReducer),
  __reducerSchema("request_appointment", RequestAppointmentReducer),
  __reducerSchema("respond_to_care_need", RespondToCareNeedReducer),
  __reducerSchema("review_appointment_summary", ReviewAppointmentSummaryReducer),
  __reducerSchema("revoke_clinician_share", RevokeClinicianShareReducer),
  __reducerSchema("revoke_location_share", RevokeLocationShareReducer),
  __reducerSchema("save_care_profile", SaveCareProfileReducer),
  __reducerSchema("save_cooking_profile", SaveCookingProfileReducer),
  __reducerSchema("save_medicine_ar_pin", SaveMedicineArPinReducer),
  __reducerSchema("send_clinician_share", SendClinicianShareReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_alert_threshold", SetAlertThresholdReducer),
  __reducerSchema("set_care_grant", SetCareGrantReducer),
  __reducerSchema("set_contact_ladder", SetContactLadderReducer),
  __reducerSchema("set_family_push_token", SetFamilyPushTokenReducer),
  __reducerSchema("set_medicine_memory", SetMedicineMemoryReducer),
  __reducerSchema("set_my_name", SetMyNameReducer),
  __reducerSchema("set_reminder_settings", SetReminderSettingsReducer),
  __reducerSchema("set_report_email_settings", SetReportEmailSettingsReducer),
  __reducerSchema("set_speaker_settings", SetSpeakerSettingsReducer),
  __reducerSchema("settle_report_email", SettleReportEmailReducer),
  __reducerSchema("settle_wearer_text", SettleWearerTextReducer),
  __reducerSchema("share_location", ShareLocationReducer),
  __reducerSchema("suggest_appointment", SuggestAppointmentReducer),
  __reducerSchema("update_appointment_prep", UpdateAppointmentPrepReducer),
  __reducerSchema("update_report", UpdateReportReducer),
  __reducerSchema("verify_care_instruction", VerifyCareInstructionReducer),
  __reducerSchema("verify_exercise_plan", VerifyExercisePlanReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

