// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.2 (commit 58d2a40718c59535fd5c267e836d473298eb84d5).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcknowledgeAlertReducer from "./acknowledge_alert_reducer";
import AddCareInstructionReducer from "./add_care_instruction_reducer";
import AddFamilyMemberReducer from "./add_family_member_reducer";
import ClaimAlertDeliveryReducer from "./claim_alert_delivery_reducer";
import CreateExercisePlanReducer from "./create_exercise_plan_reducer";
import CreateFamilyReducer from "./create_family_reducer";
import CreateReportReducer from "./create_report_reducer";
import LinkFinchnodeSubjectReducer from "./link_finchnode_subject_reducer";
import MarkAlertDeliveryFailedReducer from "./mark_alert_delivery_failed_reducer";
import MarkAlertDeliverySentReducer from "./mark_alert_delivery_sent_reducer";
import MarkAlertDeliveryUnavailableReducer from "./mark_alert_delivery_unavailable_reducer";
import OpenCareNeedReducer from "./open_care_need_reducer";
import PostAlertMessageReducer from "./post_alert_message_reducer";
import RaiseAlertReducer from "./raise_alert_reducer";
import RecordExerciseEventReducer from "./record_exercise_event_reducer";
import RecordMealFactReducer from "./record_meal_fact_reducer";
import RecordSampleReducer from "./record_sample_reducer";
import RecordTripEventReducer from "./record_trip_event_reducer";
import RemoveAlertThresholdReducer from "./remove_alert_threshold_reducer";
import RespondToCareNeedReducer from "./respond_to_care_need_reducer";
import SaveCareProfileReducer from "./save_care_profile_reducer";
import SendMessageReducer from "./send_message_reducer";
import SetAlertThresholdReducer from "./set_alert_threshold_reducer";
import SetCareGrantReducer from "./set_care_grant_reducer";
import SetContactLadderReducer from "./set_contact_ladder_reducer";
import UpdateReportReducer from "./update_report_reducer";
import VerifyCareInstructionReducer from "./verify_care_instruction_reducer";
import VerifyExercisePlanReducer from "./verify_exercise_plan_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import MyAcknowledgementsRow from "./my_acknowledgements_table";
import MyAlertDeliveriesRow from "./my_alert_deliveries_table";
import MyAlertThresholdsRow from "./my_alert_thresholds_table";
import MyAlertsRow from "./my_alerts_table";
import MyCareGrantsRow from "./my_care_grants_table";
import MyCareInstructionsRow from "./my_care_instructions_table";
import MyCareNeedsRow from "./my_care_needs_table";
import MyCareProfilesRow from "./my_care_profiles_table";
import MyContactAttemptsRow from "./my_contact_attempts_table";
import MyContactLaddersRow from "./my_contact_ladders_table";
import MyExerciseEventsRow from "./my_exercise_events_table";
import MyExercisePlansRow from "./my_exercise_plans_table";
import MyFamiliesRow from "./my_families_table";
import MyFinchnodeLinksRow from "./my_finchnode_links_table";
import MyHealthSamplesRow from "./my_health_samples_table";
import MyMealFactsRow from "./my_meal_facts_table";
import MyMessagesRow from "./my_messages_table";
import MyReportsRow from "./my_reports_table";
import MyTripEventsRow from "./my_trip_events_table";
import PendingAlertDeliveriesRow from "./pending_alert_deliveries_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  myAcknowledgements: __table({
    name: 'my_acknowledgements',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAcknowledgementsRow),
  myAlertDeliveries: __table({
    name: 'my_alert_deliveries',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAlertDeliveriesRow),
  myAlertThresholds: __table({
    name: 'my_alert_thresholds',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAlertThresholdsRow),
  myAlerts: __table({
    name: 'my_alerts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAlertsRow),
  myCareGrants: __table({
    name: 'my_care_grants',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCareGrantsRow),
  myCareInstructions: __table({
    name: 'my_care_instructions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCareInstructionsRow),
  myCareNeeds: __table({
    name: 'my_care_needs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCareNeedsRow),
  myCareProfiles: __table({
    name: 'my_care_profiles',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCareProfilesRow),
  myContactAttempts: __table({
    name: 'my_contact_attempts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyContactAttemptsRow),
  myContactLadders: __table({
    name: 'my_contact_ladders',
    indexes: [
    ],
    constraints: [
    ],
  }, MyContactLaddersRow),
  myExerciseEvents: __table({
    name: 'my_exercise_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyExerciseEventsRow),
  myExercisePlans: __table({
    name: 'my_exercise_plans',
    indexes: [
    ],
    constraints: [
    ],
  }, MyExercisePlansRow),
  myFamilies: __table({
    name: 'my_families',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFamiliesRow),
  myFinchnodeLinks: __table({
    name: 'my_finchnode_links',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFinchnodeLinksRow),
  myHealthSamples: __table({
    name: 'my_health_samples',
    indexes: [
    ],
    constraints: [
    ],
  }, MyHealthSamplesRow),
  myMealFacts: __table({
    name: 'my_meal_facts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMealFactsRow),
  myMessages: __table({
    name: 'my_messages',
    indexes: [
    ],
    constraints: [
    ],
  }, MyMessagesRow),
  myReports: __table({
    name: 'my_reports',
    indexes: [
    ],
    constraints: [
    ],
  }, MyReportsRow),
  myTripEvents: __table({
    name: 'my_trip_events',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTripEventsRow),
  pendingAlertDeliveries: __table({
    name: 'pending_alert_deliveries',
    indexes: [
    ],
    constraints: [
    ],
  }, PendingAlertDeliveriesRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("acknowledge_alert", AcknowledgeAlertReducer),
  __reducerSchema("add_care_instruction", AddCareInstructionReducer),
  __reducerSchema("add_family_member", AddFamilyMemberReducer),
  __reducerSchema("claim_alert_delivery", ClaimAlertDeliveryReducer),
  __reducerSchema("create_exercise_plan", CreateExercisePlanReducer),
  __reducerSchema("create_family", CreateFamilyReducer),
  __reducerSchema("create_report", CreateReportReducer),
  __reducerSchema("link_finchnode_subject", LinkFinchnodeSubjectReducer),
  __reducerSchema("mark_alert_delivery_failed", MarkAlertDeliveryFailedReducer),
  __reducerSchema("mark_alert_delivery_sent", MarkAlertDeliverySentReducer),
  __reducerSchema("mark_alert_delivery_unavailable", MarkAlertDeliveryUnavailableReducer),
  __reducerSchema("open_care_need", OpenCareNeedReducer),
  __reducerSchema("post_alert_message", PostAlertMessageReducer),
  __reducerSchema("raise_alert", RaiseAlertReducer),
  __reducerSchema("record_exercise_event", RecordExerciseEventReducer),
  __reducerSchema("record_meal_fact", RecordMealFactReducer),
  __reducerSchema("record_sample", RecordSampleReducer),
  __reducerSchema("record_trip_event", RecordTripEventReducer),
  __reducerSchema("remove_alert_threshold", RemoveAlertThresholdReducer),
  __reducerSchema("respond_to_care_need", RespondToCareNeedReducer),
  __reducerSchema("save_care_profile", SaveCareProfileReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_alert_threshold", SetAlertThresholdReducer),
  __reducerSchema("set_care_grant", SetCareGrantReducer),
  __reducerSchema("set_contact_ladder", SetContactLadderReducer),
  __reducerSchema("update_report", UpdateReportReducer),
  __reducerSchema("verify_care_instruction", VerifyCareInstructionReducer),
  __reducerSchema("verify_exercise_plan", VerifyExercisePlanReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.10.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

