// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  DeliveryStatus,
} from "./types";


export default __t.row({
  alertId: __t.u64().primaryKey().name("alert_id"),
  familyId: __t.u64().name("family_id"),
  summary: __t.string(),
  get status() {
    return DeliveryStatus;
  },
  attempts: __t.u32(),
  notBefore: __t.timestamp().name("not_before"),
  lastError: __t.option(__t.string()).name("last_error"),
  updatedAt: __t.timestamp().name("updated_at"),
});
