// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  familyId: __t.u64().name("family_id"),
  visit: __t.string(),
  prep: __t.string(),
  source: __t.string(),
  suggestedBy: __t.identity().name("suggested_by"),
  suggestedAt: __t.timestamp().name("suggested_at"),
  requestedBy: __t.option(__t.identity()).name("requested_by"),
  requestedAt: __t.option(__t.timestamp()).name("requested_at"),
  confirmation: __t.option(__t.string()),
  confirmedBy: __t.option(__t.identity()).name("confirmed_by"),
  confirmedAt: __t.option(__t.timestamp()).name("confirmed_at"),
  cancelledBy: __t.option(__t.identity()).name("cancelled_by"),
  cancelledAt: __t.option(__t.timestamp()).name("cancelled_at"),
  summary: __t.option(__t.string()),
  summaryReviewedBy: __t.option(__t.identity()).name("summary_reviewed_by"),
  summaryReviewedAt: __t.option(__t.timestamp()).name("summary_reviewed_at"),
});
