// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  AttemptChannel,
  AttemptStatus,
} from "./types";


export default __t.row({
  key: __t.string().primaryKey(),
  needId: __t.u64().name("need_id"),
  familyId: __t.u64().name("family_id"),
  step: __t.u32(),
  member: __t.identity(),
  get channel() {
    return AttemptChannel;
  },
  get status() {
    return AttemptStatus;
  },
  body: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
