// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ContactStep,
  NeedKind,
  NeedFact,
  NeedStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.u64().name("family_id"),
  get kind() {
    return NeedKind;
  },
  summary: __t.string(),
  get facts() {
    return __t.array(NeedFact);
  },
  alertId: __t.option(__t.u64()).name("alert_id"),
  dueAt: __t.timestamp().name("due_at"),
  get steps() {
    return __t.array(ContactStep);
  },
  hasBackup: __t.bool().name("has_backup"),
  answerSeconds: __t.u32().name("answer_seconds"),
  followUpSeconds: __t.u32().name("follow_up_seconds"),
  get status() {
    return NeedStatus;
  },
  step: __t.u32(),
  acceptedBy: __t.option(__t.identity()).name("accepted_by"),
  followUpBy: __t.option(__t.timestamp()).name("follow_up_by"),
  raisedBy: __t.identity().name("raised_by"),
  clientId: __t.string().name("client_id"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
