// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.u64().name("family_id"),
  kind: __t.string(),
  name: __t.string(),
  instruction: __t.string(),
  times: __t.array(__t.string()),
  reason: __t.option(__t.string()),
  source: __t.string(),
  effectiveDate: __t.string().name("effective_date"),
  editedBy: __t.identity().name("edited_by"),
  editedAt: __t.timestamp().name("edited_at"),
  verifiedBy: __t.option(__t.identity()).name("verified_by"),
  verifiedAt: __t.option(__t.timestamp()).name("verified_at"),
});
