// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  familyId: __t.u64().name("family_id"),
  appointmentId: __t.string().name("appointment_id"),
  recipient: __t.string(),
  sections: __t.string(),
  consent: __t.string(),
  frequency: __t.string(),
  approvedBy: __t.identity().name("approved_by"),
  approvedAt: __t.timestamp().name("approved_at"),
  approvedSummaryAt: __t.option(__t.timestamp()).name("approved_summary_at"),
  revokedBy: __t.option(__t.identity()).name("revoked_by"),
  revokedAt: __t.option(__t.timestamp()).name("revoked_at"),
  sends: __t.u32(),
  lastSentAt: __t.option(__t.timestamp()).name("last_sent_at"),
});
