// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  OrderStatus,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.u64().name("family_id"),
  proposalId: __t.string().name("proposal_id"),
  get status() {
    return OrderStatus;
  },
  proposal: __t.option(__t.string()),
  note: __t.string(),
  actor: __t.identity(),
  at: __t.timestamp(),
});
