// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  familyId: __t.u64().name("family_id"),
  planId: __t.string().name("plan_id"),
  sessionId: __t.string().name("session_id"),
  kind: __t.string(),
  reason: __t.option(__t.string()),
  actor: __t.identity(),
  at: __t.timestamp(),
});
