// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  HomePoint,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.u64().name("family_id"),
  sharer: __t.identity(),
  get home() {
    return __t.option(HomePoint);
  },
  radiusMeters: __t.u32().name("radius_meters"),
  autoTrip: __t.bool().name("auto_trip"),
  outsideSince: __t.option(__t.timestamp()).name("outside_since"),
  awaySince: __t.option(__t.timestamp()).name("away_since"),
  distanceMeters: __t.option(__t.f64()).name("distance_meters"),
  updatedAt: __t.timestamp().name("updated_at"),
});
