// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SampleQuality,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.u64().name("family_id"),
  metric: __t.string(),
  value: __t.f64(),
  unit: __t.string(),
  sourceTime: __t.timestamp().name("source_time"),
  receivedAt: __t.timestamp().name("received_at"),
  source: __t.string(),
  synthetic: __t.bool(),
  get quality() {
    return SampleQuality;
  },
  recordedBy: __t.identity().name("recorded_by"),
});
