// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.u64().name("family_id"),
  container: __t.string(),
  place: __t.string(),
  seenAt: __t.timestamp().name("seen_at"),
  source: __t.string(),
  confidence: __t.f64(),
  labelRead: __t.bool().name("label_read"),
  savedBy: __t.identity().name("saved_by"),
  notFoundAt: __t.option(__t.timestamp()).name("not_found_at"),
});
