// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  containerId: __t.u64().primaryKey().name("container_id"),
  familyId: __t.u64().name("family_id"),
  anchorId: __t.string().name("anchor_id"),
  mapBytes: __t.u32().name("map_bytes"),
  savedBy: __t.identity().name("saved_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  personId: __t.identity().name("person_id"),
});
