// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.u64().name("family_id"),
  reminderId: __t.u64().name("reminder_id"),
  slot: __t.string(),
  kind: __t.string(),
  subjectId: __t.option(__t.string()).name("subject_id"),
  title: __t.string(),
  minuteOfDay: __t.u16().name("minute_of_day"),
  scheduledFor: __t.timestamp().name("scheduled_for"),
  state: __t.string(),
  promptDue: __t.bool().name("prompt_due"),
  prompts: __t.u32(),
  nextPromptAt: __t.option(__t.timestamp()).name("next_prompt_at"),
});
