// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  occurrenceId: __t.u64().name("occurrence_id"),
  familyId: __t.u64().name("family_id"),
  state: __t.string(),
  response: __t.option(__t.string()),
  at: __t.timestamp(),
  actor: __t.option(__t.identity()),
  source: __t.string(),
  wording: __t.option(__t.string()),
});
