// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  familyId: __t.u64().primaryKey().name("family_id"),
  timeZone: __t.string().name("time_zone"),
  quietStart: __t.option(__t.u16()).name("quiet_start"),
  quietEnd: __t.option(__t.u16()).name("quiet_end"),
  repeatEveryMinutes: __t.u32().name("repeat_every_minutes"),
  maxPrompts: __t.u32().name("max_prompts"),
  snoozeMinutes: __t.u32().name("snooze_minutes"),
  updatedBy: __t.identity().name("updated_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
