// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  TripStep,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  familyId: __t.u64().name("family_id"),
  tripId: __t.string().name("trip_id"),
  get step() {
    return TripStep;
  },
  source: __t.string(),
  purpose: __t.option(__t.string()),
  destination: __t.option(__t.string()),
  notifyDeparture: __t.bool().name("notify_departure"),
  notifyArrival: __t.bool().name("notify_arrival"),
  by: __t.identity(),
  at: __t.timestamp(),
});
