// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  TripStep,
  TripPlan,
} from "./types";

export default {
  familyId: __t.u64(),
  tripId: __t.string(),
  get step() {
    return TripStep;
  },
  source: __t.string(),
  get plan() {
    return __t.option(TripPlan);
  },
};
