// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  familyId: __t.u64(),
  container: __t.string(),
  place: __t.string(),
  seenAt: __t.timestamp(),
  source: __t.string(),
  confidence: __t.f64(),
  labelRead: __t.bool(),
};
