// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  familyId: __t.u64(),
  timeZone: __t.string(),
  quietStart: __t.option(__t.u16()),
  quietEnd: __t.option(__t.u16()),
  repeatEveryMinutes: __t.u32(),
  maxPrompts: __t.u32(),
  snoozeMinutes: __t.u32(),
};
