// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ThresholdDirection,
} from "./types";

export default {
  familyId: __t.u64(),
  metric: __t.string(),
  get direction() {
    return ThresholdDirection;
  },
  limit: __t.f64(),
  unit: __t.string(),
  maxAgeSeconds: __t.u32(),
};
