// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Acknowledgement = __t.object("Acknowledgement", {
  id: __t.u64(),
  alertId: __t.u64(),
  familyId: __t.u64(),
  member: __t.identity(),
  acknowledgedAt: __t.timestamp(),
});
export type Acknowledgement = __Infer<typeof Acknowledgement>;

export const Alert = __t.object("Alert", {
  id: __t.u64(),
  familyId: __t.u64(),
  sampleId: __t.option(__t.u64()),
  summary: __t.string(),
  raisedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Alert = __Infer<typeof Alert>;

export const AlertDelivery = __t.object("AlertDelivery", {
  alertId: __t.u64(),
  familyId: __t.u64(),
  summary: __t.string(),
  get status() {
    return DeliveryStatus;
  },
  attempts: __t.u32(),
  notBefore: __t.timestamp(),
  lastError: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type AlertDelivery = __Infer<typeof AlertDelivery>;

export const AlertThreshold = __t.object("AlertThreshold", {
  id: __t.u64(),
  familyId: __t.u64(),
  metric: __t.string(),
  get direction() {
    return ThresholdDirection;
  },
  limit: __t.f64(),
  unit: __t.string(),
  maxAgeSeconds: __t.u32(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type AlertThreshold = __Infer<typeof AlertThreshold>;

// The tagged union or sum type for the algebraic type `DeliveryStatus`.
export const DeliveryStatus = __t.enum("DeliveryStatus", {
  Queued: __t.unit(),
  Sent: __t.unit(),
  Failed: __t.unit(),
  Unavailable: __t.unit(),
});
export type DeliveryStatus = __Infer<typeof DeliveryStatus>;

export const Family = __t.object("Family", {
  id: __t.u64(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Family = __Infer<typeof Family>;

export const FamilyMember = __t.object("FamilyMember", {
  id: __t.u64(),
  familyId: __t.u64(),
  member: __t.identity(),
  addedAt: __t.timestamp(),
});
export type FamilyMember = __Infer<typeof FamilyMember>;

export const FinchnodeLink = __t.object("FinchnodeLink", {
  id: __t.u64(),
  familyId: __t.u64(),
  subject: __t.string(),
  synthetic: __t.bool(),
  linkedBy: __t.identity(),
  linkedAt: __t.timestamp(),
});
export type FinchnodeLink = __Infer<typeof FinchnodeLink>;

export const HealthSample = __t.object("HealthSample", {
  id: __t.u64(),
  familyId: __t.u64(),
  metric: __t.string(),
  value: __t.f64(),
  unit: __t.string(),
  sourceTime: __t.timestamp(),
  receivedAt: __t.timestamp(),
  source: __t.string(),
  synthetic: __t.bool(),
  get quality() {
    return SampleQuality;
  },
  recordedBy: __t.identity(),
});
export type HealthSample = __Infer<typeof HealthSample>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  familyId: __t.u64(),
  sender: __t.identity(),
  body: __t.string(),
  sentAt: __t.timestamp(),
  clientId: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const MyAcknowledgements = __t.object("MyAcknowledgements", {});
export type MyAcknowledgements = __Infer<typeof MyAcknowledgements>;

export const MyAlertDeliveries = __t.object("MyAlertDeliveries", {});
export type MyAlertDeliveries = __Infer<typeof MyAlertDeliveries>;

export const MyAlertThresholds = __t.object("MyAlertThresholds", {});
export type MyAlertThresholds = __Infer<typeof MyAlertThresholds>;

export const MyAlerts = __t.object("MyAlerts", {});
export type MyAlerts = __Infer<typeof MyAlerts>;

export const MyFamilies = __t.object("MyFamilies", {});
export type MyFamilies = __Infer<typeof MyFamilies>;

export const MyFinchnodeLinks = __t.object("MyFinchnodeLinks", {});
export type MyFinchnodeLinks = __Infer<typeof MyFinchnodeLinks>;

export const MyHealthSamples = __t.object("MyHealthSamples", {});
export type MyHealthSamples = __Infer<typeof MyHealthSamples>;

export const MyMessages = __t.object("MyMessages", {});
export type MyMessages = __Infer<typeof MyMessages>;

export const MyReports = __t.object("MyReports", {});
export type MyReports = __Infer<typeof MyReports>;

export const Operator = __t.object("Operator", {
  identity: __t.identity(),
});
export type Operator = __Infer<typeof Operator>;

export const PendingAlertDeliveries = __t.object("PendingAlertDeliveries", {});
export type PendingAlertDeliveries = __Infer<typeof PendingAlertDeliveries>;

export const PendingDelivery = __t.object("PendingDelivery", {
  alertId: __t.u64(),
  familyId: __t.u64(),
  summary: __t.string(),
  get status() {
    return DeliveryStatus;
  },
  attempts: __t.u32(),
  notBefore: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PendingDelivery = __Infer<typeof PendingDelivery>;

export const Report = __t.object("Report", {
  id: __t.string(),
  familyId: __t.u64(),
  markers: __t.string(),
  fields: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  reviewedBy: __t.option(__t.identity()),
  reviewedAt: __t.option(__t.timestamp()),
});
export type Report = __Infer<typeof Report>;

// The tagged union or sum type for the algebraic type `SampleQuality`.
export const SampleQuality = __t.enum("SampleQuality", {
  Validated: __t.unit(),
  Unvalidated: __t.unit(),
});
export type SampleQuality = __Infer<typeof SampleQuality>;

// The tagged union or sum type for the algebraic type `ThresholdDirection`.
export const ThresholdDirection = __t.enum("ThresholdDirection", {
  Above: __t.unit(),
  Below: __t.unit(),
});
export type ThresholdDirection = __Infer<typeof ThresholdDirection>;

export const ThresholdTrigger = __t.object("ThresholdTrigger", {
  key: __t.string(),
  alertId: __t.u64(),
});
export type ThresholdTrigger = __Infer<typeof ThresholdTrigger>;

