// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Acknowledgement = __t.object("Acknowledgement", {
  id: __t.u64(),
  alertId: __t.u64(),
  familyId: __t.u64(),
  member: __t.identity(),
  acknowledgedAt: __t.timestamp(),
});
export type Acknowledgement = __Infer<typeof Acknowledgement>;

export const Alert = __t.object("Alert", {
  id: __t.u64(),
  familyId: __t.u64(),
  sampleId: __t.option(__t.u64()),
  summary: __t.string(),
  raisedBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Alert = __Infer<typeof Alert>;

export const AlertDelivery = __t.object("AlertDelivery", {
  alertId: __t.u64(),
  familyId: __t.u64(),
  summary: __t.string(),
  get status() {
    return DeliveryStatus;
  },
  attempts: __t.u32(),
  notBefore: __t.timestamp(),
  lastError: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type AlertDelivery = __Infer<typeof AlertDelivery>;

export const AlertThreshold = __t.object("AlertThreshold", {
  id: __t.u64(),
  familyId: __t.u64(),
  metric: __t.string(),
  get direction() {
    return ThresholdDirection;
  },
  limit: __t.f64(),
  unit: __t.string(),
  maxAgeSeconds: __t.u32(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type AlertThreshold = __Infer<typeof AlertThreshold>;

// The tagged union or sum type for the algebraic type `AttemptChannel`.
export const AttemptChannel = __t.enum("AttemptChannel", {
  Call: __t.unit(),
  Message: __t.unit(),
});
export type AttemptChannel = __Infer<typeof AttemptChannel>;

// The tagged union or sum type for the algebraic type `AttemptStatus`.
export const AttemptStatus = __t.enum("AttemptStatus", {
  Queued: __t.unit(),
  Sent: __t.unit(),
  Delivered: __t.unit(),
  Answered: __t.unit(),
  Accepted: __t.unit(),
  Declined: __t.unit(),
  NoAnswer: __t.unit(),
  FollowUpExpired: __t.unit(),
});
export type AttemptStatus = __Infer<typeof AttemptStatus>;

export const CareGrantEvent = __t.object("CareGrantEvent", {
  id: __t.u64(),
  familyId: __t.u64(),
  member: __t.identity(),
  scope: __t.string(),
  granted: __t.bool(),
  changedBy: __t.identity(),
  changedAt: __t.timestamp(),
});
export type CareGrantEvent = __Infer<typeof CareGrantEvent>;

export const CareInstruction = __t.object("CareInstruction", {
  id: __t.u64(),
  familyId: __t.u64(),
  kind: __t.string(),
  name: __t.string(),
  instruction: __t.string(),
  times: __t.array(__t.string()),
  reason: __t.option(__t.string()),
  source: __t.string(),
  effectiveDate: __t.string(),
  editedBy: __t.identity(),
  editedAt: __t.timestamp(),
  verifiedBy: __t.option(__t.identity()),
  verifiedAt: __t.option(__t.timestamp()),
});
export type CareInstruction = __Infer<typeof CareInstruction>;

export const CareNeed = __t.object("CareNeed", {
  id: __t.u64(),
  familyId: __t.u64(),
  get kind() {
    return NeedKind;
  },
  summary: __t.string(),
  get facts() {
    return __t.array(NeedFact);
  },
  alertId: __t.option(__t.u64()),
  dueAt: __t.timestamp(),
  get steps() {
    return __t.array(ContactStep);
  },
  hasBackup: __t.bool(),
  answerSeconds: __t.u32(),
  followUpSeconds: __t.u32(),
  get status() {
    return NeedStatus;
  },
  step: __t.u32(),
  acceptedBy: __t.option(__t.identity()),
  followUpBy: __t.option(__t.timestamp()),
  raisedBy: __t.identity(),
  clientId: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CareNeed = __Infer<typeof CareNeed>;

export const CareProfileVersion = __t.object("CareProfileVersion", {
  id: __t.u64(),
  familyId: __t.u64(),
  profile: __t.string(),
  editedBy: __t.identity(),
  editedAt: __t.timestamp(),
});
export type CareProfileVersion = __Infer<typeof CareProfileVersion>;

export const ContactAttempt = __t.object("ContactAttempt", {
  key: __t.string(),
  needId: __t.u64(),
  familyId: __t.u64(),
  step: __t.u32(),
  member: __t.identity(),
  get channel() {
    return AttemptChannel;
  },
  get status() {
    return AttemptStatus;
  },
  body: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ContactAttempt = __Infer<typeof ContactAttempt>;

// The tagged union or sum type for the algebraic type `ContactDetail`.
export const ContactDetail = __t.enum("ContactDetail", {
  Minimal: __t.unit(),
  Summary: __t.unit(),
  Facts: __t.unit(),
});
export type ContactDetail = __Infer<typeof ContactDetail>;

export const ContactLadder = __t.object("ContactLadder", {
  familyId: __t.u64(),
  get contacts() {
    return __t.array(ContactStep);
  },
  get backup() {
    return __t.option(ContactStep);
  },
  answerSeconds: __t.u32(),
  followUpSeconds: __t.u32(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type ContactLadder = __Infer<typeof ContactLadder>;

export const ContactStep = __t.object("ContactStep", {
  member: __t.identity(),
  name: __t.string(),
  timeZone: __t.string(),
  get detail() {
    return ContactDetail;
  },
  get callFor() {
    return __t.array(NeedKind);
  },
});
export type ContactStep = __Infer<typeof ContactStep>;

// The tagged union or sum type for the algebraic type `DeliveryStatus`.
export const DeliveryStatus = __t.enum("DeliveryStatus", {
  Queued: __t.unit(),
  Sent: __t.unit(),
  Failed: __t.unit(),
  Unavailable: __t.unit(),
});
export type DeliveryStatus = __Infer<typeof DeliveryStatus>;

export const ExerciseEvent = __t.object("ExerciseEvent", {
  id: __t.string(),
  familyId: __t.u64(),
  planId: __t.string(),
  sessionId: __t.string(),
  kind: __t.string(),
  reason: __t.option(__t.string()),
  actor: __t.identity(),
  at: __t.timestamp(),
});
export type ExerciseEvent = __Infer<typeof ExerciseEvent>;

export const ExercisePlan = __t.object("ExercisePlan", {
  id: __t.string(),
  familyId: __t.u64(),
  plan: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  verifiedBy: __t.option(__t.identity()),
  verifiedAt: __t.option(__t.timestamp()),
});
export type ExercisePlan = __Infer<typeof ExercisePlan>;

export const Family = __t.object("Family", {
  id: __t.u64(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Family = __Infer<typeof Family>;

export const FamilyMember = __t.object("FamilyMember", {
  id: __t.u64(),
  familyId: __t.u64(),
  member: __t.identity(),
  addedAt: __t.timestamp(),
});
export type FamilyMember = __Infer<typeof FamilyMember>;

export const FinchnodeLink = __t.object("FinchnodeLink", {
  id: __t.u64(),
  familyId: __t.u64(),
  subject: __t.string(),
  synthetic: __t.bool(),
  linkedBy: __t.identity(),
  linkedAt: __t.timestamp(),
});
export type FinchnodeLink = __Infer<typeof FinchnodeLink>;

export const HealthSample = __t.object("HealthSample", {
  id: __t.u64(),
  familyId: __t.u64(),
  metric: __t.string(),
  value: __t.f64(),
  unit: __t.string(),
  sourceTime: __t.timestamp(),
  receivedAt: __t.timestamp(),
  source: __t.string(),
  synthetic: __t.bool(),
  get quality() {
    return SampleQuality;
  },
  recordedBy: __t.identity(),
});
export type HealthSample = __Infer<typeof HealthSample>;

export const LadderTimer = __t.object("LadderTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  needId: __t.u64(),
  step: __t.u32(),
  get purpose() {
    return LadderTimerPurpose;
  },
});
export type LadderTimer = __Infer<typeof LadderTimer>;

// The tagged union or sum type for the algebraic type `LadderTimerPurpose`.
export const LadderTimerPurpose = __t.enum("LadderTimerPurpose", {
  Send: __t.unit(),
  AnswerDue: __t.unit(),
  FollowUpDue: __t.unit(),
});
export type LadderTimerPurpose = __Infer<typeof LadderTimerPurpose>;

export const MealFact = __t.object("MealFact", {
  id: __t.u64(),
  familyId: __t.u64(),
  mealId: __t.string(),
  fact: __t.string(),
  recordedBy: __t.identity(),
  recordedAt: __t.timestamp(),
});
export type MealFact = __Infer<typeof MealFact>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  familyId: __t.u64(),
  sender: __t.identity(),
  body: __t.string(),
  sentAt: __t.timestamp(),
  clientId: __t.string(),
});
export type Message = __Infer<typeof Message>;

export const MyAcknowledgements = __t.object("MyAcknowledgements", {});
export type MyAcknowledgements = __Infer<typeof MyAcknowledgements>;

export const MyAlertDeliveries = __t.object("MyAlertDeliveries", {});
export type MyAlertDeliveries = __Infer<typeof MyAlertDeliveries>;

export const MyAlertThresholds = __t.object("MyAlertThresholds", {});
export type MyAlertThresholds = __Infer<typeof MyAlertThresholds>;

export const MyAlerts = __t.object("MyAlerts", {});
export type MyAlerts = __Infer<typeof MyAlerts>;

export const MyCareGrants = __t.object("MyCareGrants", {});
export type MyCareGrants = __Infer<typeof MyCareGrants>;

export const MyCareInstructions = __t.object("MyCareInstructions", {});
export type MyCareInstructions = __Infer<typeof MyCareInstructions>;

export const MyCareNeeds = __t.object("MyCareNeeds", {});
export type MyCareNeeds = __Infer<typeof MyCareNeeds>;

export const MyCareProfiles = __t.object("MyCareProfiles", {});
export type MyCareProfiles = __Infer<typeof MyCareProfiles>;

export const MyContactAttempts = __t.object("MyContactAttempts", {});
export type MyContactAttempts = __Infer<typeof MyContactAttempts>;

export const MyContactLadders = __t.object("MyContactLadders", {});
export type MyContactLadders = __Infer<typeof MyContactLadders>;

export const MyExerciseEvents = __t.object("MyExerciseEvents", {});
export type MyExerciseEvents = __Infer<typeof MyExerciseEvents>;

export const MyExercisePlans = __t.object("MyExercisePlans", {});
export type MyExercisePlans = __Infer<typeof MyExercisePlans>;

export const MyFamilies = __t.object("MyFamilies", {});
export type MyFamilies = __Infer<typeof MyFamilies>;

export const MyFinchnodeLinks = __t.object("MyFinchnodeLinks", {});
export type MyFinchnodeLinks = __Infer<typeof MyFinchnodeLinks>;

export const MyHealthSamples = __t.object("MyHealthSamples", {});
export type MyHealthSamples = __Infer<typeof MyHealthSamples>;

export const MyMealFacts = __t.object("MyMealFacts", {});
export type MyMealFacts = __Infer<typeof MyMealFacts>;

export const MyMessages = __t.object("MyMessages", {});
export type MyMessages = __Infer<typeof MyMessages>;

export const MyReports = __t.object("MyReports", {});
export type MyReports = __Infer<typeof MyReports>;

export const NeedFact = __t.object("NeedFact", {
  text: __t.string(),
  source: __t.string(),
  observedAt: __t.timestamp(),
  uncertainty: __t.string(),
});
export type NeedFact = __Infer<typeof NeedFact>;

// The tagged union or sum type for the algebraic type `NeedKind`.
export const NeedKind = __t.enum("NeedKind", {
  Alert: __t.unit(),
  Help: __t.unit(),
  CallReminder: __t.unit(),
});
export type NeedKind = __Infer<typeof NeedKind>;

// The tagged union or sum type for the algebraic type `NeedResponse`.
export const NeedResponse = __t.enum("NeedResponse", {
  Seen: __t.unit(),
  Answer: __t.unit(),
  Accept: __t.unit(),
  Decline: __t.unit(),
  ConfirmHelp: __t.unit(),
});
export type NeedResponse = __Infer<typeof NeedResponse>;

// The tagged union or sum type for the algebraic type `NeedStatus`.
export const NeedStatus = __t.enum("NeedStatus", {
  Open: __t.unit(),
  Accepted: __t.unit(),
  Resolved: __t.unit(),
  Unresolved: __t.unit(),
});
export type NeedStatus = __Infer<typeof NeedStatus>;

export const Operator = __t.object("Operator", {
  identity: __t.identity(),
});
export type Operator = __Infer<typeof Operator>;

export const PendingAlertDeliveries = __t.object("PendingAlertDeliveries", {});
export type PendingAlertDeliveries = __Infer<typeof PendingAlertDeliveries>;

export const PendingDelivery = __t.object("PendingDelivery", {
  alertId: __t.u64(),
  familyId: __t.u64(),
  summary: __t.string(),
  get status() {
    return DeliveryStatus;
  },
  attempts: __t.u32(),
  notBefore: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type PendingDelivery = __Infer<typeof PendingDelivery>;

export const Report = __t.object("Report", {
  id: __t.string(),
  familyId: __t.u64(),
  markers: __t.string(),
  fields: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  reviewedBy: __t.option(__t.identity()),
  reviewedAt: __t.option(__t.timestamp()),
});
export type Report = __Infer<typeof Report>;

// The tagged union or sum type for the algebraic type `SampleQuality`.
export const SampleQuality = __t.enum("SampleQuality", {
  Validated: __t.unit(),
  Unvalidated: __t.unit(),
});
export type SampleQuality = __Infer<typeof SampleQuality>;

// The tagged union or sum type for the algebraic type `ThresholdDirection`.
export const ThresholdDirection = __t.enum("ThresholdDirection", {
  Above: __t.unit(),
  Below: __t.unit(),
});
export type ThresholdDirection = __Infer<typeof ThresholdDirection>;

export const ThresholdTrigger = __t.object("ThresholdTrigger", {
  key: __t.string(),
  alertId: __t.u64(),
});
export type ThresholdTrigger = __Infer<typeof ThresholdTrigger>;

