// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcknowledgeAlertReducer from "../acknowledge_alert_reducer";
import AddFamilyMemberReducer from "../add_family_member_reducer";
import ClaimAlertDeliveryReducer from "../claim_alert_delivery_reducer";
import CreateFamilyReducer from "../create_family_reducer";
import MarkAlertDeliveryFailedReducer from "../mark_alert_delivery_failed_reducer";
import MarkAlertDeliverySentReducer from "../mark_alert_delivery_sent_reducer";
import MarkAlertDeliveryUnavailableReducer from "../mark_alert_delivery_unavailable_reducer";
import RaiseAlertReducer from "../raise_alert_reducer";
import RecordSampleReducer from "../record_sample_reducer";
import RemoveAlertThresholdReducer from "../remove_alert_threshold_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetAlertThresholdReducer from "../set_alert_threshold_reducer";

export type AcknowledgeAlertParams = __Infer<typeof AcknowledgeAlertReducer>;
export type AddFamilyMemberParams = __Infer<typeof AddFamilyMemberReducer>;
export type ClaimAlertDeliveryParams = __Infer<typeof ClaimAlertDeliveryReducer>;
export type CreateFamilyParams = __Infer<typeof CreateFamilyReducer>;
export type MarkAlertDeliveryFailedParams = __Infer<typeof MarkAlertDeliveryFailedReducer>;
export type MarkAlertDeliverySentParams = __Infer<typeof MarkAlertDeliverySentReducer>;
export type MarkAlertDeliveryUnavailableParams = __Infer<typeof MarkAlertDeliveryUnavailableReducer>;
export type RaiseAlertParams = __Infer<typeof RaiseAlertReducer>;
export type RecordSampleParams = __Infer<typeof RecordSampleReducer>;
export type RemoveAlertThresholdParams = __Infer<typeof RemoveAlertThresholdReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetAlertThresholdParams = __Infer<typeof SetAlertThresholdReducer>;

