// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcknowledgeAlertReducer from "../acknowledge_alert_reducer";
import AddFamilyMemberReducer from "../add_family_member_reducer";
import AnswerReminderReducer from "../answer_reminder_reducer";
import ClaimAlertDeliveryReducer from "../claim_alert_delivery_reducer";
import ConfirmReminderReducer from "../confirm_reminder_reducer";
import CreateFamilyReducer from "../create_family_reducer";
import CreateReminderReducer from "../create_reminder_reducer";
import CreateReportReducer from "../create_report_reducer";
import DeleteReminderReducer from "../delete_reminder_reducer";
import LinkFinchnodeSubjectReducer from "../link_finchnode_subject_reducer";
import MarkAlertDeliveryFailedReducer from "../mark_alert_delivery_failed_reducer";
import MarkAlertDeliverySentReducer from "../mark_alert_delivery_sent_reducer";
import MarkAlertDeliveryUnavailableReducer from "../mark_alert_delivery_unavailable_reducer";
import OpenCareNeedReducer from "../open_care_need_reducer";
import RaiseAlertReducer from "../raise_alert_reducer";
import RecordReminderDeliveryReducer from "../record_reminder_delivery_reducer";
import RecordSampleReducer from "../record_sample_reducer";
import RemoveAlertThresholdReducer from "../remove_alert_threshold_reducer";
import RespondToCareNeedReducer from "../respond_to_care_need_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetAlertThresholdReducer from "../set_alert_threshold_reducer";
import SetContactLadderReducer from "../set_contact_ladder_reducer";
import SetReminderSettingsReducer from "../set_reminder_settings_reducer";
import UpdateReportReducer from "../update_report_reducer";

export type AcknowledgeAlertParams = __Infer<typeof AcknowledgeAlertReducer>;
export type AddFamilyMemberParams = __Infer<typeof AddFamilyMemberReducer>;
export type AnswerReminderParams = __Infer<typeof AnswerReminderReducer>;
export type ClaimAlertDeliveryParams = __Infer<typeof ClaimAlertDeliveryReducer>;
export type ConfirmReminderParams = __Infer<typeof ConfirmReminderReducer>;
export type CreateFamilyParams = __Infer<typeof CreateFamilyReducer>;
export type CreateReminderParams = __Infer<typeof CreateReminderReducer>;
export type CreateReportParams = __Infer<typeof CreateReportReducer>;
export type DeleteReminderParams = __Infer<typeof DeleteReminderReducer>;
export type LinkFinchnodeSubjectParams = __Infer<typeof LinkFinchnodeSubjectReducer>;
export type MarkAlertDeliveryFailedParams = __Infer<typeof MarkAlertDeliveryFailedReducer>;
export type MarkAlertDeliverySentParams = __Infer<typeof MarkAlertDeliverySentReducer>;
export type MarkAlertDeliveryUnavailableParams = __Infer<typeof MarkAlertDeliveryUnavailableReducer>;
export type OpenCareNeedParams = __Infer<typeof OpenCareNeedReducer>;
export type RaiseAlertParams = __Infer<typeof RaiseAlertReducer>;
export type RecordReminderDeliveryParams = __Infer<typeof RecordReminderDeliveryReducer>;
export type RecordSampleParams = __Infer<typeof RecordSampleReducer>;
export type RemoveAlertThresholdParams = __Infer<typeof RemoveAlertThresholdReducer>;
export type RespondToCareNeedParams = __Infer<typeof RespondToCareNeedReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetAlertThresholdParams = __Infer<typeof SetAlertThresholdReducer>;
export type SetContactLadderParams = __Infer<typeof SetContactLadderReducer>;
export type SetReminderSettingsParams = __Infer<typeof SetReminderSettingsReducer>;
export type UpdateReportParams = __Infer<typeof UpdateReportReducer>;

