// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcknowledgeAlertReducer from "../acknowledge_alert_reducer";
import AddCareInstructionReducer from "../add_care_instruction_reducer";
import AddFamilyMemberReducer from "../add_family_member_reducer";
import ClaimAlertDeliveryReducer from "../claim_alert_delivery_reducer";
import CreateExercisePlanReducer from "../create_exercise_plan_reducer";
import CreateFamilyReducer from "../create_family_reducer";
import CreateReportReducer from "../create_report_reducer";
import LinkFinchnodeSubjectReducer from "../link_finchnode_subject_reducer";
import MarkAlertDeliveryFailedReducer from "../mark_alert_delivery_failed_reducer";
import MarkAlertDeliverySentReducer from "../mark_alert_delivery_sent_reducer";
import MarkAlertDeliveryUnavailableReducer from "../mark_alert_delivery_unavailable_reducer";
import OpenCareNeedReducer from "../open_care_need_reducer";
import PostAlertMessageReducer from "../post_alert_message_reducer";
import RaiseAlertReducer from "../raise_alert_reducer";
import RecordExerciseEventReducer from "../record_exercise_event_reducer";
import RecordMealFactReducer from "../record_meal_fact_reducer";
import RecordSampleReducer from "../record_sample_reducer";
import RemoveAlertThresholdReducer from "../remove_alert_threshold_reducer";
import ReportLocationReducer from "../report_location_reducer";
import RespondToCareNeedReducer from "../respond_to_care_need_reducer";
import RevokeLocationShareReducer from "../revoke_location_share_reducer";
import SaveCareProfileReducer from "../save_care_profile_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetAlertThresholdReducer from "../set_alert_threshold_reducer";
import SetCareGrantReducer from "../set_care_grant_reducer";
import SetContactLadderReducer from "../set_contact_ladder_reducer";
import ShareLocationReducer from "../share_location_reducer";
import UpdateReportReducer from "../update_report_reducer";
import VerifyCareInstructionReducer from "../verify_care_instruction_reducer";
import VerifyExercisePlanReducer from "../verify_exercise_plan_reducer";

export type AcknowledgeAlertParams = __Infer<typeof AcknowledgeAlertReducer>;
export type AddCareInstructionParams = __Infer<typeof AddCareInstructionReducer>;
export type AddFamilyMemberParams = __Infer<typeof AddFamilyMemberReducer>;
export type ClaimAlertDeliveryParams = __Infer<typeof ClaimAlertDeliveryReducer>;
export type CreateExercisePlanParams = __Infer<typeof CreateExercisePlanReducer>;
export type CreateFamilyParams = __Infer<typeof CreateFamilyReducer>;
export type CreateReportParams = __Infer<typeof CreateReportReducer>;
export type LinkFinchnodeSubjectParams = __Infer<typeof LinkFinchnodeSubjectReducer>;
export type MarkAlertDeliveryFailedParams = __Infer<typeof MarkAlertDeliveryFailedReducer>;
export type MarkAlertDeliverySentParams = __Infer<typeof MarkAlertDeliverySentReducer>;
export type MarkAlertDeliveryUnavailableParams = __Infer<typeof MarkAlertDeliveryUnavailableReducer>;
export type OpenCareNeedParams = __Infer<typeof OpenCareNeedReducer>;
export type PostAlertMessageParams = __Infer<typeof PostAlertMessageReducer>;
export type RaiseAlertParams = __Infer<typeof RaiseAlertReducer>;
export type RecordExerciseEventParams = __Infer<typeof RecordExerciseEventReducer>;
export type RecordMealFactParams = __Infer<typeof RecordMealFactReducer>;
export type RecordSampleParams = __Infer<typeof RecordSampleReducer>;
export type RemoveAlertThresholdParams = __Infer<typeof RemoveAlertThresholdReducer>;
export type ReportLocationParams = __Infer<typeof ReportLocationReducer>;
export type RespondToCareNeedParams = __Infer<typeof RespondToCareNeedReducer>;
export type RevokeLocationShareParams = __Infer<typeof RevokeLocationShareReducer>;
export type SaveCareProfileParams = __Infer<typeof SaveCareProfileReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetAlertThresholdParams = __Infer<typeof SetAlertThresholdReducer>;
export type SetCareGrantParams = __Infer<typeof SetCareGrantReducer>;
export type SetContactLadderParams = __Infer<typeof SetContactLadderReducer>;
export type ShareLocationParams = __Infer<typeof ShareLocationReducer>;
export type UpdateReportParams = __Infer<typeof UpdateReportReducer>;
export type VerifyCareInstructionParams = __Infer<typeof VerifyCareInstructionReducer>;
export type VerifyExercisePlanParams = __Infer<typeof VerifyExercisePlanReducer>;

